import image1 from "../../../assets/image 1 (5).png";
import image2 from "../../../assets/image 2.png";
import image3 from "../../../assets/image 3.png";
import image4 from "../../../assets/image 4 (1).png";
import image5 from "../../../assets/image 9 (1).png";
import image6 from "../../../assets/image 6 (4).png";
import image7 from "../../../assets/image 7.jpg";
import image8 from "../../../assets/image 8.jpg";

const OurProductObject = [
  {
    id: 1,
    image: image1,
    Category: "Synltherine",
    Title: "Stylish cafe chair",
    Price: "2.500.00",
  },
  {
    id: 2,
    image: image2,
    Category: "Leviosa",
    Title: "Stylish cafe chair",
    Price: "2.500.00",
  },
  {
    id: 3,
    image: image3,
    Category: "Lolito",
    Title: "Luxury big sofa",
    Price: "7.000.00",
  },
  {
    id: 4,
    image: image4,
    Category: "Respira",
    Title: "Outdoor bar table and stool",
    Price: "500.00",
  },
  {
    id: 5,
    image: image5,
    Category: "Grifo",
    Title: "Night lamp",
    Price: "2.500.00",
  },
  {
    id: 6,
    image: image6,
    Category: "Muggo",
    Title: "Small mug",
    Price: "150.00",
  },
  {
    id: 7,
    image: image7,
    Category: "Pingky",
    Title: "CUte bed set",
    Price: "7.000.00",
  },
  {
    id: 8,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 9,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 10,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 11,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 12,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 13,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 14,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 15,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 16,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 17,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 18,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 19,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 20,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 21,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 22,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 23,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 24,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 25,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 26,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 27,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 28,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 29,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 30,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 31,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 32,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 33,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 34,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 35,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 36,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 37,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 38,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 39,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 40,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 41,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 42,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
  {
    id: 43,
    image: image8,
    Category: "Potty",
    Title: "Minimalist flower pot",
    Price: "500.00",
  },
];
export default OurProductObject;
